
package com.bglhqx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSInterface", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param machineid
     * @param fromtime
     * @param endtime
     * @param point
     * @return
     *     returns com.bglhqx.PIReturnObject
     */
    @WebMethod(operationName = "QueryRealData", action = "http://tempuri.org/WSInterface/QueryRealData")
    @WebResult(name = "QueryRealDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryRealData", targetNamespace = "http://tempuri.org/", className = "com.bglhqx.QueryRealData")
    @ResponseWrapper(localName = "QueryRealDataResponse", targetNamespace = "http://tempuri.org/", className = "com.bglhqx.QueryRealDataResponse")
    @Action(input = "http://tempuri.org/WSInterface/QueryRealData", output = "http://tempuri.org/WSInterface/QueryRealDataResponse")
    public PIReturnObject queryRealData(
        @WebParam(name = "machineid", targetNamespace = "http://tempuri.org/")
        String machineid,
        @WebParam(name = "point", targetNamespace = "http://tempuri.org/")
        String point,
        @WebParam(name = "fromtime", targetNamespace = "http://tempuri.org/")
        String fromtime,
        @WebParam(name = "endtime", targetNamespace = "http://tempuri.org/")
        String endtime);

    /**
     * 
     * @param machineid
     * @param fromtime
     * @param endtime
     * @param point
     * @return
     *     returns com.bglhqx.PIReturnObject
     */
    @WebMethod(operationName = "QueryRealData1", action = "http://tempuri.org/WSInterface/QueryRealData1")
    @WebResult(name = "QueryRealData1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryRealData1", targetNamespace = "http://tempuri.org/", className = "com.bglhqx.QueryRealData1")
    @ResponseWrapper(localName = "QueryRealData1Response", targetNamespace = "http://tempuri.org/", className = "com.bglhqx.QueryRealData1Response")
    @Action(input = "http://tempuri.org/WSInterface/QueryRealData1", output = "http://tempuri.org/WSInterface/QueryRealData1Response")
    public PIReturnObject queryRealData1(
        @WebParam(name = "machineid", targetNamespace = "http://tempuri.org/")
        String machineid,
        @WebParam(name = "point", targetNamespace = "http://tempuri.org/")
        String point,
        @WebParam(name = "fromtime", targetNamespace = "http://tempuri.org/")
        String fromtime,
        @WebParam(name = "endtime", targetNamespace = "http://tempuri.org/")
        String endtime);

}
