/**
 * 上海蓝鸟集团
 * 上海蓝鸟科技股份有限公司
 * 2018版权所有
 */
package com.bluebirdme.mes.linglong.finalcheck.controller;

import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.annotation.Resource;

import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.xdemo.app.xutils.ext.GsonTools;
import org.xdemo.app.xutils.j2se.StringUtils;

import com.bluebirdme.core.system.annotations.Log;
import com.bluebirdme.core.system.annotations.NoLogin;
import com.bluebirdme.core.system.annotations.support.LogType;
import com.bluebirdme.core.system.spring.SpringContext;
import com.bluebirdme.core.system.web.Filter;
import com.bluebirdme.core.system.web.Page;
import com.bluebirdme.core.system.web.Response;
import com.bluebirdme.mes.linglong.common.service.ExportServiceImpl;
import com.bluebirdme.mes.linglong.core.RockWellBaseServiceImpl;
import com.bluebirdme.mes.linglong.core.RockWellFunctionalController;
import com.bluebirdme.mes.linglong.core.RockWellFunctionalUDAController;
import com.bluebirdme.mes.linglong.core.RockWellUDABaseServiceImpl;
import com.bluebirdme.mes.linglong.core.utils.LLWebUtils;
import com.bluebirdme.mes.linglong.finalcheck.entity.Checkuniformlog;
import com.bluebirdme.mes.linglong.finalcheck.service.CheckuniformlogServiceImpl;

/**
 * 质检均匀机检测履历表_全钢
 * @author 周志祥
 * @Date 2019-05-02 10:00:12
 */
@Log(code="Checkuniformlog_log",value="质检均匀机检测_log")
@RestController
@RequestMapping("finalcheck/qualityInspectionRecord/checkuniformlog")
public class CheckuniformlogController extends RockWellFunctionalUDAController<Object> {
    
    @Resource CheckuniformlogServiceImpl checkuniformlogSrv;
    public ExportServiceImpl exportServiceImpl = (ExportServiceImpl) SpringContext.getBean(StringUtils
			.firstCharToLowerCase("exportServiceImpl"));
    @Override
    protected RockWellBaseServiceImpl<Object> getService() {
        return checkuniformlogSrv;
    }
    @Override
	protected RockWellUDABaseServiceImpl<Object> getUDAService() {
    	return checkuniformlogSrv;
	}
    

    @Override
	@Log(value = "查询列表", code = "ALL", target = LogType.CONSOLE)
	@ResponseBody
	@RequestMapping("datagrid")
	public String datagrid(Filter filter, Page page) throws Exception {
		filter.set("s_factory_s", LLWebUtils.factory());
		/*if(filter.getFilter().containsKey("barcode_s")){
			filter.set("begin_created_time","");
			filter.set("end_created_time","");
		}*/
		return  GsonTools.toJson(getUDAService().datagridUDA(filter, page));
	}
    
    @Log(code = "ZJ_BZGL_RKFJ_SAVE_ENTNAME", value = "获取均匀性光机")
	@RequestMapping("combox_entcode")
	public String combox_entcode() throws Exception {
		List<Map<String, Object>> list = checkuniformlogSrv.getEntCodeName();
		return toJson(list);
	}
    

	@NoLogin
	@Log(value = "导出CSV", code = "ZJ_JCGL_DPHJCLL_EXPORT_CSV")
	@RequestMapping("exportCSV")
	public void exportCSV(String s_factory_s,String machinebar_s,String curingspeccode_s,String barcode_s,String begin_created_time,String end_created_time) throws Exception{
    	Filter filter=new Filter();
    	filter.setSort("t.atr_key");
    	filter.setOrder("asc");
	    filter.set("machinebar_s", machinebar_s)
			  .set("curingspeccode_s", curingspeccode_s)
			  .set("barcode_s", barcode_s)
			  .set("s_factory_s", s_factory_s)
			  .set("begin_created_time", begin_created_time)
			  .set("end_created_time", end_created_time);
    	System.out.println(filter);
		// 每次查询2000条导入
		int batchQueryCount = 1000;

		Page page = new Page();
		page.setRows(batchQueryCount);
		page.setAll(0);
        page.setPage(1);
		int pageNum = 1;
		
		response.reset();
		
		response.setHeader("content-disposition", "attachment;filename="
				+ new String("均匀性检测履历.csv".getBytes("GBK"), "ISO-8859-1"));
		
		String title="均匀性机台,轮胎条码,物料编码,物料描述,检测时间,成型机台,成型时间,硫化机台,硫化时间,轮胎总等级,跳动度总等级,均匀性总等级,径向力波动值,径向力波动角度,径向力波动等级 ,径向力波动一次谐波值,径向力波动一次谐角度,径向力波动一次谐波等级,径向力波动二次谐波值,径向力波动二次谐波角度,径向力波动二次谐波等级,径向力波动三次谐波值,径向力波动三次谐波角度,径向力波动三次谐波等级,径向力波动四次谐波值,径向力波动四次谐波角度,径向力波动四次谐波等级,径向力波动五次谐波值,径向力波动五次谐波角度,径向力波动五次谐波等级,径向力波动六次谐波值,径向力波动六次谐波角度,径向力波动六次谐波等级,径向力波动七次谐波值,径向力波动七次谐波角度,径向力波动七次谐波等级,径向力波动八次谐波值,径向力波动八次谐波角度,径向力波动八次谐波等级,径向力波动九次谐波值,径向力波动九次谐波角度,径向力波动九次谐波等级,径向力波动十次谐波值,径向力波动十次谐波角度,径向力波动十次谐波等级,侧向力波动值,侧向力波动角度,侧向力波动等级,侧向力波动一次谐波值,侧向力波动一次谐角度,侧向力波动一次谐波等级,侧向力波动二次谐波值,侧向力波动二次谐波角度,侧向力波动二次谐波角等级,侧向力波动三次谐波值,侧向力波动三次谐波角度,侧向力波动三次谐波等级,侧向力波动四次谐波值,侧向力波动四次谐波角度,侧向力波动四次谐波等级,侧向力波动五次谐波值,侧向力波动五次谐波角度,侧向力波动五次谐波等级,侧向力波动六次谐波值,侧向力波动六次谐波角度,侧向力波动六次谐波等级,侧向力波动七次谐波值,侧向力波动七次谐波角度,侧向力波动七次谐波等级,侧向力波动八次谐波值,侧向力波动八次谐波角度,侧向力波动八次谐波等级,侧向力波动九次谐波值,侧向力波动九次谐波角度,侧向力波动九次谐波等级,侧向力波动十次谐波值,侧向力波动十次谐波角度,侧向力波动十次谐波等级,正转侧向力偏移值,正转侧向力偏移等级,反转径向力波动值,反转径向力波动角度,反转径向力波动角等级,反转径向力波动一次谐波值,反转径向力波动一次谐波角度,反转径向力波动一次谐波等级,反转径向力波动二次谐波值,反转径向力波动二次谐波角度,反转径向力波动二次谐波等级,反转径向力波动三次谐波值,反转径向力波动三次谐波角度,反转径向力波动三次谐波等级,反转径向力波动四次谐波值,反转径向力波动四次谐波角度,反转径向力波动四次谐波等级,反转径向力波动五次谐波值,反转径向力波动五次谐波角度,反转径向力波动五次谐波等级,反转径向力波动六次谐波值,反转径向力波动六次谐波角度,反转径向力波动六次谐波等级,反转径向力波动七次谐波值,反转径向力波动七次谐波角度,反转径向力波动七次谐波等级,反转径向力波动八次谐波值,反转径向力波动八次谐波角度,反转径向力波动八次谐波等级,反转径向力波动九次谐波值,反转径向力波动九次谐波角度,反转径向力波动九次谐波等级,反转径向力波动十次谐波值,反转径向力波动十次谐波角度,反转径向力波动十次谐波等级,反转侧向力波动值,反转侧向力波动角度,反转侧向力波动等级,反转侧向力波动一次谐波值,反转侧向力波动一次谐波角度,反转侧向力波动一次谐波等级,反转侧向力波动二次谐波值,反转侧向力波动二次谐波角度,反转侧向力波动二次谐波等级,反转侧向力波动三次谐波值,反转侧向力波动三次谐波角度,反转侧向力波动三次谐波等级,反转侧向力波动四次谐波值,反转侧向力波动四次谐波角度,反转侧向力波动四次谐波等级,反转侧向力波动五次谐波值,反转侧向力波动五次谐波角度,反转侧向力波动五次谐波等级,反转侧向力波动六次谐波值,反转侧向力波动六次谐波角度,反转侧向力波动六次谐波等级,反转侧向力波动七次谐波值,反转侧向力波动七次谐波角度,反转侧向力波动七次谐波等级,反转侧向力波动八次谐波值,反转侧向力波动八次谐波角度,反转侧向力波动八次谐波等级,反转侧向力波动九次谐波值,反转侧向力波动九次谐波角度,反转侧向力波动九次谐波等级,反转侧向力波动十次谐波值,反转侧向力波动十次谐波角度,反转侧向力波动十次谐波等级,反转侧向力偏移值,反转侧向力偏移等级,锥度值,锥度等级,帘布效应,帘布效应等级,上部侧向跳动值,上部侧向跳动角度,上部侧向跳动等级,上部侧向跳动一次谐波值,上部侧向跳动一次谐波角度,上部侧向跳动一次谐波等级,下部侧向跳动值,下部侧向跳动角度,下部侧向跳动等级,下部侧向跳动一次谐波值,下部侧向跳动一次谐波角度,下部侧向跳动一次谐波等级,上部径向跳动值,上部径向跳动角度,上部径向跳动等级,上部径向跳动一次谐波值,上部径向跳动一次谐波角度,上部径向跳动一次谐波等级,中部径向跳动值,中部径向跳动角度,中部径向跳动等级,中部径向跳动一次谐波值,中部径向跳动一次谐波角度,中部径向跳动一次谐波等级,下部径向跳动值,下部径向跳动角度,下部径向跳动等级,下部径向跳动一次谐波值,下部径向跳动一次谐波角度,下部径向跳动一次谐波等级,上部侧向凸值 ,上部侧向凸角度,上部侧向凸等级,上部侧向凹值,上部侧向凹角度 ,上部侧向凹等级,下部侧向凸值,下部侧向凸角度,下部侧向凸等级 ,下部侧向凹值,下部侧向凹角度 ,下部侧向凹等级,轮胎外直径,轮胎外直径等级,荷重,备注,修改人,修改时间,创建人,创建时间";
		
		StringBuffer sb=new StringBuffer();
		OutputStream writer = response.getOutputStream();
		writer.write((title+System.getProperty("line.separator")).getBytes("GBK"));//
		//缓冲输出到客户端，浏览器将立即开始下载，提高用户体验
		writer.flush();
		
		ConcurrentHashMap<String, String> machine=new ConcurrentHashMap<String,String>();
		try {
			while (true) {
				// 分页查询数据
				long t1=System.currentTimeMillis();
				System.out.println("正在查询第" + (pageNum++) + "页数据");
				
				List<Map<String,Object>> list = getUDAService().datagridRowsUDA(filter, page);
				 page.setPage(page.getPage()+ 1);
				//filter.set("atr_key", list.get(list.size()-1).getAtr_key());
				long t2=System.currentTimeMillis();
				System.out.println("数据查询完成，耗时:"+(t2-t1)+"ms");
				
				for (Map<String, Object> rs : list) {
					/*if(rs.get("gradecode_s")!=null&&machine.get(rs.get("gradecode_s"))==null){
						machine.put("gradecode_s",exportServiceImpl.getDictName(rs.get("gradecode_s").toString()));
					}*/
				    if(rs.get("gradecode_s")!=null){
						 rs.put("gradecode_s", exportServiceImpl.getDictName(rs.get("gradecode_s").toString())); 
					}
					
					if (rs.get("s_factory_s").toString().equals("2")) {
						rs.put("s_factory_s", "半钢");
					} else {
						rs.put("s_factory_s", "全钢");
					}
					sb=new StringBuffer();
					if(rs.containsKey("machinebar_s")){
						if(rs.get("machinebar_s")!=null){
							sb.append(combox_entName(rs.get("machinebar_s").toString())).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("barcode_s")){
						if(rs.get("barcode_s")!=null){
							sb.append(rs.get("barcode_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("materialcode_s")){
						if(rs.get("materialcode_s")!=null){
							sb.append(rs.get("materialcode_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("description")){
						if(rs.get("description")!=null){
							sb.append(rs.get("description").toString()).append(",\t");					
						}else{
							sb.append("").append(",\t");		
						}
					}
					if(rs.containsKey("created_time_t")){
						if(rs.get("created_time_t")!=null){
							sb.append(rs.get("created_time_t").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("buildinmachinecode_s")){
						if(rs.get("buildinmachinecode_s")!=null){
							sb.append(rs.get("buildinmachinecode_s").toString()).append(",");					
						}else{
							sb.append("补录").append(",");		
						}
					}
					if(rs.containsKey("buildintime_t")){
						if(rs.get("buildintime_t")!=null){
							sb.append(rs.get("buildintime_t").toString().substring(0, 18)).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("curingmachinecode_s")){
						if(rs.get("curingmachinecode_s")!=null){
							sb.append(rs.get("curingmachinecode_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("curingtime_t")){
						if(rs.get("curingtime_t")!=null){
							sb.append(rs.get("curingtime_t").toString().substring(0, 18)).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("gradecode_s")){
						if(rs.get("gradecode_s")!=null){
							sb.append(rs.get("gradecode_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ro_total_rank_s")){
						if(rs.get("ro_total_rank_s")!=null){
							sb.append(rs.get("ro_total_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ufm_total_rank_s")){
						if(rs.get("ufm_total_rank_s")!=null){
							sb.append(rs.get("ufm_total_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_kgf_s")){
						if(rs.get("cw_rfv_oa_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_deg_s")){
						if(rs.get("cw_rfv_oa_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_rank_s")){
						if(rs.get("cw_rfv_oa_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_1h_kgf_s")){
						if(rs.get("cw_rfv_oa_1h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_1h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_1h_deg_s")){
						if(rs.get("cw_rfv_oa_1h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_1h_rank_s")){
						if(rs.get("cw_rfv_oa_1h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_2h_kgf_s")){
						if(rs.get("cw_rfv_oa_2h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_2h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_2h_deg_s")){
						if(rs.get("cw_rfv_oa_2h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_2h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_2h_rank_s")){
						if(rs.get("cw_rfv_oa_2h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_2h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_3h_kgf_s")){
						if(rs.get("cw_rfv_oa_3h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_3h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_3h_deg_s")){
						if(rs.get("cw_rfv_oa_3h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_3h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_3h_rank_s")){
						if(rs.get("cw_rfv_oa_3h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_3h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_4h_kgf_s")){
						if(rs.get("cw_rfv_oa_4h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_4h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_4h_deg_s")){
						if(rs.get("cw_rfv_oa_4h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_4h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_4h_rank_s")){
						if(rs.get("cw_rfv_oa_4h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_4h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_5h_kgf_s")){
						if(rs.get("cw_rfv_oa_5h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_5h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_5h_deg_s")){
						if(rs.get("cw_rfv_oa_5h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_5h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_5h_rank_s")){
						if(rs.get("cw_rfv_oa_5h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_5h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_6h_kgf_s")){
						if(rs.get("cw_rfv_oa_6h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_6h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_6h_deg_s")){
						if(rs.get("cw_rfv_oa_6h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_6h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_6h_rank_s")){
						if(rs.get("cw_rfv_oa_6h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_6h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_7h_kgf_s")){
						if(rs.get("cw_rfv_oa_7h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_7h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_7h_deg_s")){
						if(rs.get("cw_rfv_oa_7h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_7h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_7h_rank_s")){
						if(rs.get("Cw_rfv_oa_7h_rank_s")!=null){
							sb.append(rs.get("Cw_rfv_oa_7h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_8h_kgf_s")){
						if(rs.get("cw_rfv_oa_8h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_8h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_8h_deg_s")){
						if(rs.get("cw_rfv_oa_8h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_8h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_8h_rank_s")){
						if(rs.get("cw_rfv_oa_8h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_8h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_9h_kgf_s")){
						if(rs.get("cw_rfv_oa_9h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_9h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_9h_deg_s")){
						if(rs.get("cw_rfv_oa_9h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_9h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_9h_rank_s")){
						if(rs.get("cw_rfv_oa_9h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_9h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_10h_kgf_s")){
						if(rs.get("cw_rfv_oa_10h_kgf_s")!=null){
							sb.append(rs.get("cw_rfv_oa_10h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_10h_deg_s")){
						if(rs.get("cw_rfv_oa_10h_deg_s")!=null){
							sb.append(rs.get("cw_rfv_oa_10h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_rfv_oa_10h_rank_s")){
						if(rs.get("cw_rfv_oa_10h_rank_s")!=null){
							sb.append(rs.get("cw_rfv_oa_10h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_kgf_s")){
						if(rs.get("cw_lfv_oa_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_deg_s")){
						if(rs.get("cw_lfv_oa_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_rank_s")){
						if(rs.get("cw_lfv_oa_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_1h_kgf_s")){
						if(rs.get("cw_lfv_oa_1h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_1h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_1h_deg_s")){
						if(rs.get("cw_lfv_oa_1h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_1h_rank_s")){
						if(rs.get("cw_lfv_oa_1h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_2h_kgf_s")){
						if(rs.get("cw_lfv_oa_2h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_2h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_2h_deg_s")){
						if(rs.get("cw_lfv_oa_2h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_2h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_2h_rank_s")){
						if(rs.get("cw_lfv_oa_2h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_2h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_3h_kgf_s")){
						if(rs.get("cw_lfv_oa_3h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_3h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_3h_deg_s")){
						if(rs.get("cw_lfv_oa_3h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_3h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_3h_rank_s")){
						if(rs.get("cw_lfv_oa_3h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_3h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_4h_kgf_s")){
						if(rs.get("cw_lfv_oa_4h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_4h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_4h_deg_s")){
						if(rs.get("cw_lfv_oa_4h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_4h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_4h_rank_s")){
						if(rs.get("cw_lfv_oa_4h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_4h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_5h_kgf_s")){
						if(rs.get("cw_lfv_oa_5h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_5h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_5h_deg_s")){
						if(rs.get("cw_lfv_oa_5h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_5h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_5h_rank_s")){
						if(rs.get("cw_lfv_oa_5h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_5h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_6h_kgf_s")){
						if(rs.get("cw_lfv_oa_6h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_6h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_6h_deg_s")){
						if(rs.get("cw_lfv_oa_6h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_6h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_6h_rank_s")){
						if(rs.get("cw_lfv_oa_6h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_6h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_7h_kgf_s")){
						if(rs.get("cw_lfv_oa_7h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_7h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_7h_deg_s")){
						if(rs.get("cw_lfv_oa_7h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_7h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_7h_rank_s")){
						if(rs.get("cw_lfv_oa_7h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_7h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_8h_kgf_s")){
						if(rs.get("cw_lfv_oa_8h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_8h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_8h_deg_s")){
						if(rs.get("cw_lfv_oa_8h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_8h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_8h_rank_s")){
						if(rs.get("cw_lfv_oa_8h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_8h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_9h_kgf_s")){
						if(rs.get("cw_lfv_oa_9h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_9h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_9h_deg_s")){
						if(rs.get("cw_lfv_oa_9h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_9h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_9h_rank_s")){
						if(rs.get("cw_lfv_oa_9h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_9h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_10h_kgf_s")){
						if(rs.get("cw_lfv_oa_10h_kgf_s")!=null){
							sb.append(rs.get("cw_lfv_oa_10h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_10h_deg_s")){
						if(rs.get("cw_lfv_oa_10h_deg_s")!=null){
							sb.append(rs.get("cw_lfv_oa_10h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfv_oa_10h_rank_s")){
						if(rs.get("cw_lfv_oa_10h_rank_s")!=null){
							sb.append(rs.get("cw_lfv_oa_10h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfd_kgf_s")){
						if(rs.get("cw_lfd_kgf_s")!=null){
							sb.append(rs.get("cw_lfd_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("cw_lfd_rank_s")){
						if(rs.get("cw_lfd_rank_s")!=null){
							sb.append(rs.get("cw_lfd_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_kgf_s")){
						if(rs.get("ccw_rfv_oa_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_deg_s")){
						if(rs.get("ccw_rfv_oa_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_rank_s")){
						if(rs.get("ccw_rfv_oa_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_1h_kgf_s")){
						if(rs.get("ccw_rfv_oa_1h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_1h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_1h_deg_s")){
						if(rs.get("ccw_rfv_oa_1h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_1h_rank_s")){
						if(rs.get("ccw_rfv_oa_1h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_2h_kgf_s")){
						if(rs.get("ccw_rfv_oa_2h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_2h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_2h_deg_s")){
						if(rs.get("ccw_rfv_oa_2h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_2h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_2h_rank_s")){
						if(rs.get("ccw_rfv_oa_2h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_2h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_3h_kgf_s")){
						if(rs.get("ccw_rfv_oa_3h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_3h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_3h_deg_s")){
						if(rs.get("ccw_rfv_oa_3h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_3h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_3h_rank_s")){
						if(rs.get("ccw_rfv_oa_3h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_3h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_4h_kgf_s")){
						if(rs.get("ccw_rfv_oa_4h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_4h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_4h_deg_s")){
						if(rs.get("ccw_rfv_oa_4h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_4h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_4h_rank_s")){
						if(rs.get("ccw_rfv_oa_4h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_4h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_5h_kgf_s")){
						if(rs.get("ccw_rfv_oa_5h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_5h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_5h_deg_s")){
						if(rs.get("ccw_rfv_oa_5h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_5h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_5h_rank_s")){
						if(rs.get("ccw_rfv_oa_5h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_5h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_6h_kgf_s")){
						if(rs.get("ccw_rfv_oa_6h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_6h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_6h_deg_s")){
						if(rs.get("ccw_rfv_oa_6h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_6h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_6h_rank_s")){
						if(rs.get("ccw_rfv_oa_6h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_6h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_7h_kgf_s")){
						if(rs.get("ccw_rfv_oa_7h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_7h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_7h_deg_s")){
						if(rs.get("ccw_rfv_oa_7h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_7h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_7h_rank_s")){
						if(rs.get("ccw_rfv_oa_7h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_7h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_8h_kgf_s")){
						if(rs.get("ccw_rfv_oa_8h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_8h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_8h_deg_s")){
						if(rs.get("ccw_rfv_oa_8h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_8h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_8h_rank_s")){
						if(rs.get("ccw_rfv_oa_8h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_8h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_9h_kgf_s")){
						if(rs.get("ccw_rfv_oa_9h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_9h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_9h_deg_s")){
						if(rs.get("ccw_rfv_oa_9h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_9h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_9h_rank_s")){
						if(rs.get("ccw_rfv_oa_9h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_9h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_10h_kgf_s")){
						if(rs.get("ccw_rfv_oa_10h_kgf_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_10h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_10h_deg_s")){
						if(rs.get("ccw_rfv_oa_10h_deg_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_10h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_rfv_oa_10h_rank_s")){
						if(rs.get("ccw_rfv_oa_10h_rank_s")!=null){
							sb.append(rs.get("ccw_rfv_oa_10h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_kgf_s")){
						if(rs.get("ccw_lfv_oa_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_deg_s")){
						if(rs.get("ccw_lfv_oa_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_rank_s")){
						if(rs.get("ccw_lfv_oa_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_1h_kgf_s")){
						if(rs.get("ccw_lfv_oa_1h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_1h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_1h_deg_s")){
						if(rs.get("ccw_lfv_oa_1h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_1h_rank_s")){
						if(rs.get("ccw_lfv_oa_1h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_2h_kgf_s")){
						if(rs.get("ccw_lfv_oa_2h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_2h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_2h_deg_s")){
						if(rs.get("ccw_lfv_oa_2h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_2h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_2h_rank_s")){
						if(rs.get("ccw_lfv_oa_2h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_2h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_3h_kgf_s")){
						if(rs.get("ccw_lfv_oa_3h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_3h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_3h_deg_s")){
						if(rs.get("ccw_lfv_oa_3h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_3h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_3h_rank_s")){
						if(rs.get("ccw_lfv_oa_3h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_3h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_4h_kgf_s")){
						if(rs.get("ccw_lfv_oa_4h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_4h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_4h_deg_s")){
						if(rs.get("ccw_lfv_oa_4h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_4h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_4h_rank_s")){
						if(rs.get("ccw_lfv_oa_4h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_4h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_5h_kgf_s")){
						if(rs.get("ccw_lfv_oa_5h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_5h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_5h_deg_s")){
						if(rs.get("ccw_lfv_oa_5h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_5h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_5h_rank_s")){
						if(rs.get("ccw_lfv_oa_5h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_5h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_6h_kgf_s")){
						if(rs.get("ccw_lfv_oa_6h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_6h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_6h_deg_s")){
						if(rs.get("ccw_lfv_oa_6h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_6h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_6h_rank_s")){
						if(rs.get("ccw_lfv_oa_6h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_6h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_7h_kgf_s")){
						if(rs.get("ccw_lfv_oa_7h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_7h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_7h_deg_s")){
						if(rs.get("ccw_lfv_oa_7h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_7h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_7h_rank_s")){
						if(rs.get("ccw_lfv_oa_7h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_7h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_8h_kgf_s")){
						if(rs.get("ccw_lfv_oa_8h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_8h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_8h_deg_s")){
						if(rs.get("ccw_lfv_oa_8h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_8h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_8h_rank_s")){
						if(rs.get("ccw_lfv_oa_8h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_8h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_9h_kgf_s")){
						if(rs.get("ccw_lfv_oa_9h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_9h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_9h_deg_s")){
						if(rs.get("ccw_lfv_oa_9h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_9h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_9h_rank_s")){
						if(rs.get("ccw_lfv_oa_9h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_9h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_10h_kgf_s")){
						if(rs.get("ccw_lfv_oa_10h_kgf_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_10h_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_10h_deg_s")){
						if(rs.get("ccw_lfv_oa_10h_deg_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_10h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfv_oa_10h_rank_s")){
						if(rs.get("ccw_lfv_oa_10h_rank_s")!=null){
							sb.append(rs.get("ccw_lfv_oa_10h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfd_kgf_s")){
						if(rs.get("ccw_lfd_kgf_s")!=null){
							sb.append(rs.get("ccw_lfd_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ccw_lfd_rank_s")){
						if(rs.get("ccw_lfd_rank_s")!=null){
							sb.append(rs.get("ccw_lfd_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("con_kgf_s")){
						if(rs.get("con_kgf_s")!=null){
							sb.append(rs.get("con_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("con_rank_s")){
						if(rs.get("con_rank_s")!=null){
							sb.append(rs.get("con_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ply_kgf_s")){
						if(rs.get("ply_kgf_s")!=null){
							sb.append(rs.get("ply_kgf_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("ply_rank_s")){
						if(rs.get("ply_rank_s")!=null){
							sb.append(rs.get("ply_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_oa_mm_s")){
						if(rs.get("lt_oa_mm_s")!=null){
							sb.append(rs.get("lt_oa_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_oa_deg_s")){
						if(rs.get("lt_oa_deg_s")!=null){
							sb.append(rs.get("lt_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_oa_rank_s")){
						if(rs.get("lt_oa_rank_s")!=null){
							sb.append(rs.get("lt_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_oa_1h_mm_s")){
						if(rs.get("lt_oa_1h_mm_s")!=null){
							sb.append(rs.get("lt_oa_1h_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_oa_1h_deg_s")){
						if(rs.get("lt_oa_1h_deg_s")!=null){
							sb.append(rs.get("lt_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_oa_1h_rank_s")){
						if(rs.get("lt_oa_1h_rank_s")!=null){
							sb.append(rs.get("lt_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_oa_mm_s")){
						if(rs.get("lb_oa_mm_s")!=null){
							sb.append(rs.get("lb_oa_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_oa_deg_s")){
						if(rs.get("lb_oa_deg_s")!=null){
							sb.append(rs.get("lb_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_oa_rank_s")){
						if(rs.get("lb_oa_rank_s")!=null){
							sb.append(rs.get("lb_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_oa_1h_mm_s")){
						if(rs.get("lb_oa_1h_mm_s")!=null){
							sb.append(rs.get("lb_oa_1h_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_oa_1h_deg_s")){
						if(rs.get("lb_oa_1h_deg_s")!=null){
							sb.append(rs.get("lb_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_oa_1h_rank_s")){
						if(rs.get("lb_oa_1h_rank_s")!=null){
							sb.append(rs.get("lb_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rt_oa_mm_s")){
						if(rs.get("rt_oa_mm_s")!=null){
							sb.append(rs.get("rt_oa_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rt_oa_deg_s")){
						if(rs.get("rt_oa_deg_s")!=null){
							sb.append(rs.get("rt_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rt_oa_rank_s")){
						if(rs.get("rt_oa_rank_s")!=null){
							sb.append(rs.get("rt_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rt_oa_1h_mm_s")){
						if(rs.get("rt_oa_1h_mm_s")!=null){
							sb.append(rs.get("rt_oa_1h_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rt_oa_1h_deg_s")){
						if(rs.get("rt_oa_1h_deg_s")!=null){
							sb.append(rs.get("rt_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rt_oa_1h_rank_s")){
						if(rs.get("rt_oa_1h_rank_s")!=null){
							sb.append(rs.get("rt_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rc_oa_mm_s")){
						if(rs.get("rc_oa_mm_s")!=null){
							sb.append(rs.get("rc_oa_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rc_oa_deg_s")){
						if(rs.get("rc_oa_deg_s")!=null){
							sb.append(rs.get("rc_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rc_oa_rank_s")){
						if(rs.get("rc_oa_rank_s")!=null){
							sb.append(rs.get("rc_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rc_oa_1h_mm_s")){
						if(rs.get("rc_oa_1h_mm_s")!=null){
							sb.append(rs.get("rc_oa_1h_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rc_oa_1h_deg_s")){
						if(rs.get("rc_oa_1h_deg_s")!=null){
							sb.append(rs.get("rc_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rc_oa_1h_rank_s")){
						if(rs.get("rc_oa_1h_rank_s")!=null){
							sb.append(rs.get("rc_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rb_oa_mm_s")){
						if(rs.get("rb_oa_mm_s")!=null){
							sb.append(rs.get("rb_oa_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rb_oa_deg_s")){
						if(rs.get("rb_oa_deg_s")!=null){
							sb.append(rs.get("rb_oa_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rb_oa_rank_s")){
						if(rs.get("rb_oa_rank_s")!=null){
							sb.append(rs.get("rb_oa_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rb_oa_1h_mm_s")){
						if(rs.get("rb_oa_1h_mm_s")!=null){
							sb.append(rs.get("rb_oa_1h_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rb_oa_1h_deg_s")){
						if(rs.get("rb_oa_1h_deg_s")!=null){
							sb.append(rs.get("rb_oa_1h_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("rb_oa_1h_rank_s")){
						if(rs.get("rb_oa_1h_rank_s")!=null){
							sb.append(rs.get("rb_oa_1h_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_bulging_mm_s")){
						if(rs.get("lt_bulging_mm_s")!=null){
							sb.append(rs.get("lt_bulging_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_bulging_deg_s")){
						if(rs.get("lt_bulging_deg_s")!=null){
							sb.append(rs.get("lt_bulging_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_bulging_rank_s")){
						if(rs.get("lt_bulging_rank_s")!=null){
							sb.append(rs.get("lt_bulging_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_dent_mm_s")){
						if(rs.get("lt_dent_mm_s")!=null){
							sb.append(rs.get("lt_dent_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_dent_deg_s")){
						if(rs.get("lt_dent_deg_s")!=null){
							sb.append(rs.get("lt_dent_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lt_dent_rank_s")){
						if(rs.get("lt_dent_rank_s")!=null){
							sb.append(rs.get("lt_dent_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_bulging_mm_s")){
						if(rs.get("lb_bulging_mm_s")!=null){
							sb.append(rs.get("lb_bulging_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_bulging_deg_s")){
						if(rs.get("lb_bulging_deg_s")!=null){
							sb.append(rs.get("lb_bulging_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_bulging_rank_s")){
						if(rs.get("lb_bulging_rank_s")!=null){
							sb.append(rs.get("lb_bulging_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_dent_mm_s")){
						if(rs.get("lb_dent_mm_s")!=null){
							sb.append(rs.get("lb_dent_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_dent_deg_s")){
						if(rs.get("lb_dent_deg_s")!=null){
							sb.append(rs.get("lb_dent_deg_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("lb_dent_rank_s")){
						if(rs.get("lb_dent_rank_s")!=null){
							sb.append(rs.get("lb_dent_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("outside_diameter_mm_s")){
						if(rs.get("outside_diameter_mm_s")!=null){
							sb.append(rs.get("outside_diameter_mm_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("outside_diameter_rank_s")){
						if(rs.get("outside_diameter_rank_s")!=null){
							sb.append(rs.get("outside_diameter_rank_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("load_s")){
						if(rs.get("load_s")!=null){
							sb.append(rs.get("load_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("memo_s")){
						if(rs.get("memo_s")!=null){
							sb.append(rs.get("memo_s").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("changed_by_s")){
						if(rs.get("changed_by_s")!=null){
							sb.append(rs.get("changed_by_s").toString()).append(",\t");					
						}else{
							sb.append("").append(",\t");		
						}
					}
					if(rs.containsKey("changed_time_t")){
						if(rs.get("changed_time_t")!=null){
							sb.append(rs.get("changed_time_t").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					if(rs.containsKey("created_by_s")){
						if(rs.get("created_by_s")!=null){
							sb.append(rs.get("created_by_s").toString()).append(",\t");					
						}else{
							sb.append("").append(",\t");		
						}
					}
					if(rs.containsKey("created_time_t")){
						if(rs.get("created_time_t")!=null){
							sb.append(rs.get("created_time_t").toString()).append(",");					
						}else{
							sb.append("").append(",");		
						}
					}
					writer.write((sb.toString().replace("\n", " ").replace("\r", " ").replace("null", "") +System.getProperty("line.separator")).getBytes("GBK"));
					writer.flush();
				}
				if (list.size() < batchQueryCount) {
					break;
				}
				long t3=System.currentTimeMillis();
				System.out.println("第"+(pageNum-1)+"页数据输出完成，耗时:"+(t3-t2)+"ms");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}finally{
			writer.flush();
			writer.close();
		}
	}
	@Log(code = "ZJ_BZGL_RKFJ_SAVE_ENTNAME", value = "获取均匀性机")
	@RequestMapping("combox_entName")
	public String combox_entName(String entCode) throws Exception {
		String result = checkuniformlogSrv.getEndNameByEntCode(entCode);
		return result;
	}
}
