package com.bluebirdme.mes.linglong.wsdl.mixserviceex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MESWSInterface", targetNamespace = "http://tempuri.org/")
public interface MESWSInterface {

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param planNo
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveWoCreateByMES")
	@WebResult(name = "reciveWoCreateByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveWoCreateByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoCreateByMES")
	@ResponseWrapper(localName = "reciveWoCreateByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoCreateByMESResponse")
	public String reciveWoCreateByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "plan_No", targetNamespace = "http://tempuri.org/") String planNo,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param parameters
	 * @return returns com.bluebirdme.mes.linglong.wsdl.mixserviceex.
	 *         RecivePolyProdByMesResponse
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/recivePolyProdByMes")
	@WebResult(name = "recivePolyProdByMesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
	@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
	public RecivePolyProdByMesResponse recivePolyTrainProdByMES(
			@WebParam(name = "recivePolyProdByMes", targetNamespace = "http://tempuri.org/", partName = "parameters") RecivePolyProdByMes parameters);

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param woNo
	 * @param addQty
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveMaterialApplyAddQtyByMES")
	@WebResult(name = "reciveMaterialApplyAddQtyByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveMaterialApplyAddQtyByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveMaterialApplyAddQtyByMES")
	@ResponseWrapper(localName = "reciveMaterialApplyAddQtyByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveMaterialApplyAddQtyByMESResponse")
	public String reciveMaterialApplyAddQtyByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "wo_No", targetNamespace = "http://tempuri.org/") String woNo,
			@WebParam(name = "add_Qty", targetNamespace = "http://tempuri.org/") Long addQty,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param equipCode
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveFeedSwitchSendByMES")
	@WebResult(name = "reciveFeedSwitchSendByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveFeedSwitchSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveFeedSwitchSendByMES")
	@ResponseWrapper(localName = "reciveFeedSwitchSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveFeedSwitchSendByMESResponse")
	public String reciveFeedSwitchSendByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "equip_Code", targetNamespace = "http://tempuri.org/") String equipCode,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param moveFlag
	 * @param planNo
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/recivePlanMoveByMES")
	@WebResult(name = "recivePlanMoveByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "recivePlanMoveByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.RecivePlanMoveByMES")
	@ResponseWrapper(localName = "recivePlanMoveByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.RecivePlanMoveByMESResponse")
	public String recivePlanMoveByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "plan_No", targetNamespace = "http://tempuri.org/") String planNo,
			@WebParam(name = "moveFlag", targetNamespace = "http://tempuri.org/") String moveFlag,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param woNo
	 * @param moveFlag
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveWoMoveByMES")
	@WebResult(name = "reciveWoMoveByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveWoMoveByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoMoveByMES")
	@ResponseWrapper(localName = "reciveWoMoveByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoMoveByMESResponse")
	public String reciveWoMoveByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "wo_No", targetNamespace = "http://tempuri.org/") String woNo,
			@WebParam(name = "moveFlag", targetNamespace = "http://tempuri.org/") String moveFlag,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param masterName
	 * @param woShift
	 * @param sendName
	 * @param masterBy
	 * @param operateFlag
	 * @param sendBy
	 * @param equipCode
	 * @param password
	 * @param user
	 * @param woDate
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveMixerMasterByMES")
	@WebResult(name = "reciveMixerMasterByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveMixerMasterByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveMixerMasterByMES")
	@ResponseWrapper(localName = "reciveMixerMasterByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveMixerMasterByMESResponse")
	public String reciveMixerMasterByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "operateFlag", targetNamespace = "http://tempuri.org/") String operateFlag,
			@WebParam(name = "wo_Date", targetNamespace = "http://tempuri.org/") String woDate,
			@WebParam(name = "wo_Shift", targetNamespace = "http://tempuri.org/") String woShift,
			@WebParam(name = "equip_Code", targetNamespace = "http://tempuri.org/") String equipCode,
			@WebParam(name = "master_By", targetNamespace = "http://tempuri.org/") String masterBy,
			@WebParam(name = "master_Name", targetNamespace = "http://tempuri.org/") String masterName,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param planNo
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveMaterialApplyByMES")
	@WebResult(name = "reciveMaterialApplyByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveMaterialApplyByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveMaterialApplyByMES")
	@ResponseWrapper(localName = "reciveMaterialApplyByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveMaterialApplyByMESResponse")
	public String reciveMaterialApplyByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "plan_No", targetNamespace = "http://tempuri.org/") String planNo,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param closeBy
	 * @param closeName
	 * @param woNo
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveWoCloseByMES")
	@WebResult(name = "reciveWoCloseByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveWoCloseByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoCloseByMES")
	@ResponseWrapper(localName = "reciveWoCloseByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoCloseByMESResponse")
	public String reciveWoCloseByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "wo_No", targetNamespace = "http://tempuri.org/") String woNo,
			@WebParam(name = "close_By", targetNamespace = "http://tempuri.org/") String closeBy,
			@WebParam(name = "close_Name", targetNamespace = "http://tempuri.org/") String closeName);

	/**
	 * 
	 * @param sendName
	 * @param sendBy
	 * @param planNo
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveWoSendByMES")
	@WebResult(name = "reciveWoSendByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveWoSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoSendByMES")
	@ResponseWrapper(localName = "reciveWoSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveWoSendByMESResponse")
	public String reciveWoSendByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "plan_No", targetNamespace = "http://tempuri.org/") String planNo,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

	/**
	 * 
	 * @param id
	 * @param sendName
	 * @param sendBy
	 * @param password
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/MESWSInterface/reciveSiloMaterialSendByMES")
	@WebResult(name = "reciveSiloMaterialSendByMESResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "reciveSiloMaterialSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveSiloMaterialSendByMES")
	@ResponseWrapper(localName = "reciveSiloMaterialSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.mixserviceex.ReciveSiloMaterialSendByMESResponse")
	public String reciveSiloMaterialSendByMES(
			@WebParam(name = "user", targetNamespace = "http://tempuri.org/") String user,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id,
			@WebParam(name = "send_By", targetNamespace = "http://tempuri.org/") String sendBy,
			@WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/") String sendName);

}
