package com.bluebirdme.mes.linglong.wsdl.mixserviceex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MESWSImplementService service = new MESWSImplementService();
 * MESWSInterface portType = service.getMESWSImplementPort();
 * portType.reciveWoCreateByMES(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MESWSImplementService", targetNamespace = "http://webservice.mes.linglong.com/", wsdlLocation = "file:/H:/myeclipse_workspace/JMmes/src/main/java/com/bluebirdme/mes/linglong/wsdl/mixserviceex/MESWSImplement.wsdl")
public class MESWSImplementService extends Service {

	private final static URL MESWSIMPLEMENTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.bluebirdme.mes.linglong.wsdl.mixserviceex.MESWSImplementService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.bluebirdme.mes.linglong.wsdl.mixserviceex.MESWSImplementService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/H:/myeclipse_workspace/JMmes/src/main/java/com/bluebirdme/mes/linglong/wsdl/mixserviceex/MESWSImplement.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/H:/myeclipse_workspace/JMmes/src/main/java/com/bluebirdme/mes/linglong/wsdl/mixserviceex/MESWSImplement.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MESWSIMPLEMENTSERVICE_WSDL_LOCATION = url;
	}

	public MESWSImplementService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MESWSImplementService() {
		super(MESWSIMPLEMENTSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.mes.linglong.com/", "MESWSImplementService"));
	}

	/**
	 * 
	 * @return returns MESWSInterface
	 */
	@WebEndpoint(name = "MESWSImplementPort")
	public MESWSInterface getMESWSImplementPort() {
		return super.getPort(new QName("http://webservice.mes.linglong.com/",
				"MESWSImplementPort"), MESWSInterface.class);
	}

}
