
package com.bluebirdme.mes.linglong.wsdl.plmserviceex;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSExInterface", targetNamespace = "http://tempuri.org/")
public interface WSExInterface {


    /**
     * 
     * @param recipeCode
     * @param sendName
     * @param sendBy
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveMixRecipeReSendByMES")
    @WebResult(name = "reciveMixRecipeReSendByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveMixRecipeReSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeReSendByMES")
    @ResponseWrapper(localName = "reciveMixRecipeReSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeReSendByMESResponse")
    public String reciveMixRecipeReSendByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "send_By", targetNamespace = "http://tempuri.org/")
        String sendBy,
        @WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/")
        String sendName);

    /**
     * 
     * @param recipeCode
     * @param checkName
     * @param checkBy
     * @param recipeCheckState
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveMixRecipeCheckByMES")
    @WebResult(name = "reciveMixRecipeCheckByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveMixRecipeCheckByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeCheckByMES")
    @ResponseWrapper(localName = "reciveMixRecipeCheckByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeCheckByMESResponse")
    public String reciveMixRecipeCheckByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "recipeCheckState", targetNamespace = "http://tempuri.org/")
        String recipeCheckState,
        @WebParam(name = "check_By", targetNamespace = "http://tempuri.org/")
        String checkBy,
        @WebParam(name = "check_Name", targetNamespace = "http://tempuri.org/")
        String checkName);

    /**
     * 
     * @param processID
     * @param factory
     * @param password
     * @param user
     * @return
     *     returns com.bluebirdme.mes.linglong.wsdl.plmserviceex.ArrayOfHalfPartRecipePara
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/getHalfPartRecipeParas")
    @WebResult(name = "getHalfPartRecipeParasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getHalfPartRecipeParas", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.GetHalfPartRecipeParas")
    @ResponseWrapper(localName = "getHalfPartRecipeParasResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.GetHalfPartRecipeParasResponse")
    public ArrayOfHalfPartRecipePara getHalfPartRecipeParas(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "processID", targetNamespace = "http://tempuri.org/")
        String processID,
        @WebParam(name = "factory", targetNamespace = "http://tempuri.org/")
        String factory);

    /**
     * 
     * @param recipeCode
     * @param sendName
     * @param sendBy
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveMixRecipeSendByMES")
    @WebResult(name = "reciveMixRecipeSendByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveMixRecipeSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeSendByMES")
    @ResponseWrapper(localName = "reciveMixRecipeSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeSendByMESResponse")
    public String reciveMixRecipeSendByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "send_By", targetNamespace = "http://tempuri.org/")
        String sendBy,
        @WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/")
        String sendName);

    /**
     * 
     * @param changedBy
     * @param id
     * @param setWeight
     * @param changedName
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveMixRecipeWeightByMES")
    @WebResult(name = "reciveMixRecipeWeightByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveMixRecipeWeightByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeWeightByMES")
    @ResponseWrapper(localName = "reciveMixRecipeWeightByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeWeightByMESResponse")
    public String reciveMixRecipeWeightByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "set_Weight", targetNamespace = "http://tempuri.org/")
        BigDecimal setWeight,
        @WebParam(name = "changed_By", targetNamespace = "http://tempuri.org/")
        String changedBy,
        @WebParam(name = "changed_Name", targetNamespace = "http://tempuri.org/")
        String changedName);

    /**
     * 
     * @param recipeCode
     * @param sendName
     * @param sendBy
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveQuickCheckRecipeSendByMES")
    @WebResult(name = "reciveQuickCheckRecipeSendByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveQuickCheckRecipeSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveQuickCheckRecipeSendByMES")
    @ResponseWrapper(localName = "reciveQuickCheckRecipeSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveQuickCheckRecipeSendByMESResponse")
    public String reciveQuickCheckRecipeSendByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "send_By", targetNamespace = "http://tempuri.org/")
        String sendBy,
        @WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/")
        String sendName);

    /**
     * 
     * @param processID
     * @param factory
     * @param password
     * @param user
     * @return
     *     returns com.bluebirdme.mes.linglong.wsdl.plmserviceex.ArrayOfBuildRecipePara
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/getBuildRecipeParas")
    @WebResult(name = "getBuildRecipeParasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getBuildRecipeParas", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.GetBuildRecipeParas")
    @ResponseWrapper(localName = "getBuildRecipeParasResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.GetBuildRecipeParasResponse")
    public ArrayOfBuildRecipePara getBuildRecipeParas(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "processID", targetNamespace = "http://tempuri.org/")
        String processID,
        @WebParam(name = "factory", targetNamespace = "http://tempuri.org/")
        String factory);

    /**
     * 
     * @param recipeCode
     * @param planQty
     * @param password
     * @param user
     * @return
     *     returns com.bluebirdme.mes.linglong.wsdl.plmserviceex.ArrayOfIntPlmMixWeight
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveMaterialApplyByMES")
    @WebResult(name = "reciveMaterialApplyByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveMaterialApplyByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMaterialApplyByMES")
    @ResponseWrapper(localName = "reciveMaterialApplyByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMaterialApplyByMESResponse")
    public ArrayOfIntPlmMixWeight reciveMaterialApplyByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "plan_Qty", targetNamespace = "http://tempuri.org/")
        Integer planQty);

    /**
     * 
     * @param recipeCode
     * @param recipeName
     * @param recipeBy
     * @param recipeStatus
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveQuickCheckRecipeStartOrStopByMES")
    @WebResult(name = "reciveQuickCheckRecipeStartOrStopByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveQuickCheckRecipeStartOrStopByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveQuickCheckRecipeStartOrStopByMES")
    @ResponseWrapper(localName = "reciveQuickCheckRecipeStartOrStopByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveQuickCheckRecipeStartOrStopByMESResponse")
    public String reciveQuickCheckRecipeStartOrStopByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "recipeStatus", targetNamespace = "http://tempuri.org/")
        String recipeStatus,
        @WebParam(name = "recipe_By", targetNamespace = "http://tempuri.org/")
        String recipeBy,
        @WebParam(name = "recipe_Name", targetNamespace = "http://tempuri.org/")
        String recipeName);

    /**
     * 
     * @param recipeCode
     * @param sendName
     * @param sendBy
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveDynamicBalanceRecipeSendByMES")
    @WebResult(name = "reciveDynamicBalanceRecipeSendByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveDynamicBalanceRecipeSendByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveDynamicBalanceRecipeSendByMES")
    @ResponseWrapper(localName = "reciveDynamicBalanceRecipeSendByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveDynamicBalanceRecipeSendByMESResponse")
    public String reciveDynamicBalanceRecipeSendByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "send_By", targetNamespace = "http://tempuri.org/")
        String sendBy,
        @WebParam(name = "send_Name", targetNamespace = "http://tempuri.org/")
        String sendName);

    /**
     * 
     * @param recipeCode
     * @param recipeName
     * @param recipeBy
     * @param recipeStatus
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveMixRecipeStartOrStopByMES")
    @WebResult(name = "reciveMixRecipeStartOrStopByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveMixRecipeStartOrStopByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeStartOrStopByMES")
    @ResponseWrapper(localName = "reciveMixRecipeStartOrStopByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveMixRecipeStartOrStopByMESResponse")
    public String reciveMixRecipeStartOrStopByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "recipeStatus", targetNamespace = "http://tempuri.org/")
        String recipeStatus,
        @WebParam(name = "recipe_By", targetNamespace = "http://tempuri.org/")
        String recipeBy,
        @WebParam(name = "recipe_Name", targetNamespace = "http://tempuri.org/")
        String recipeName);

    /**
     * 
     * @param recipeCode
     * @param recipeName
     * @param recipeBy
     * @param recipeStatus
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/WSExInterface/reciveDynamicBalanceRecipeStartOrStopByMES")
    @WebResult(name = "reciveDynamicBalanceRecipeStartOrStopByMESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "reciveDynamicBalanceRecipeStartOrStopByMES", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveDynamicBalanceRecipeStartOrStopByMES")
    @ResponseWrapper(localName = "reciveDynamicBalanceRecipeStartOrStopByMESResponse", targetNamespace = "http://tempuri.org/", className = "com.bluebirdme.mes.linglong.wsdl.plmserviceex.ReciveDynamicBalanceRecipeStartOrStopByMESResponse")
    public String reciveDynamicBalanceRecipeStartOrStopByMES(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "recipe_Code", targetNamespace = "http://tempuri.org/")
        String recipeCode,
        @WebParam(name = "recipeStatus", targetNamespace = "http://tempuri.org/")
        String recipeStatus,
        @WebParam(name = "recipe_By", targetNamespace = "http://tempuri.org/")
        String recipeBy,
        @WebParam(name = "recipe_Name", targetNamespace = "http://tempuri.org/")
        String recipeName);

}
