package com.bluebirdme.mes.linglong.wsdl.plmserviceex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WSImplementService service = new WSImplementService();
 * WSExInterface portType = service.getWSImplementPort();
 * portType.reciveMixRecipeReSendByMES(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WSImplementService", targetNamespace = "http://webserviceex.plm.linglong.com/", wsdlLocation = "http://192.168.55.43:10001/PLMServiceEx?wsdl")
public class WSImplementService extends Service {

	private final static URL WSIMPLEMENTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.bluebirdme.mes.linglong.wsdl.plmserviceex.WSImplementService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.bluebirdme.mes.linglong.wsdl.plmserviceex.WSImplementService.class.getResource(".");
			url = new URL(baseUrl, "http://192.168.55.43:10001/PLMServiceEx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.55.43:10001/PLMServiceEx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSIMPLEMENTSERVICE_WSDL_LOCATION = url;
	}

	public WSImplementService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WSImplementService() {
		super(WSIMPLEMENTSERVICE_WSDL_LOCATION,
				new QName("http://webserviceex.plm.linglong.com/", "WSImplementService"));
	}

	/**
	 * 
	 * @return returns WSExInterface
	 */
	@WebEndpoint(name = "WSImplementPort")
	public WSExInterface getWSImplementPort() {
		return super
				.getPort(new QName("http://webserviceex.plm.linglong.com/", "WSImplementPort"), WSExInterface.class);
	}

}
